
export const APP_LOAD = 'APP_LOAD';
export const LOGIN = 'LOGIN';
export const LOGIN_UNLOAD = 'LOGIN_UNLOAD';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const UNAUTH = 'UNAUTH';
export const REDIRECT = 'REDIRECT';
export const HAS_ERROR = 'HAS_ERROR';
export const SHOW_ERROR = 'SHOW_ERROR';

export const USERS_LOADED = "USER_LOADED";
export const USERS_SET_PAGE = "USER_SET_PAGE";
export const USER_DETAIL_LOADED = "USER_DETAIL_LOADED";
export const USER_FORM = "USER_FORM";
export const USER_UPDATE_FIELD = "USER_UPDATE_FIELD";
export const USER_SUBMIT = "USER_SUBMIT";
export const USER_RESET_PASSWORD = "USER_RESET_PASSWORD";
export const USER_CHANGE_PASSWORD = "USER_CHANGE_PASSWORD";
export const USER_APPROVE = "USER_APPROVE";
export const USER_CANCEL = "USER_CANCEL";
export const USER_CREATE = "USER_CREATE";
export const USER_DELETE = "USER_DELETE";
export const USER_UNLOAD = "USER_UNLOAD";

export const PERMISSIONS_LOADED = 'PERMISSIONS_LOADED';
export const PERMISSION_DETAIL_LOADED = 'PERMISSION_DETAIL_LOADED';
export const PERMISSION_MODULE_LOADED = 'PERMISSION_MODULE_LOADED';
export const PERMISSION_UPDATE_FIELD = 'PERMISSION_UPDATE_FIELD';
export const PERMISSION_SUBMIT = 'PERMISSION_SUBMIT';
export const PERMISSION_CREATE = 'PERMISSION_CREATE';
export const PERMISSION_UNLOAD = 'PERMISSION_UNLOAD';

export const MODULE_LOADED = 'MODULE_LOADED';
export const MODULE_DETAIL_LOADED = 'MODULE_DETAIL_LOADED';
export const MODULE_MODULE_LOADED = 'MODULE_MODULE_LOADED';
export const MODULE_UPDATE_FIELD = 'MODULE_UPDATE_FIELD';
export const MODULE_ADD_ACTION = 'MODULE_ADD_ACTION';
export const MODULE_REMOVE_ACTION = 'MODULE_REMOVE_ACTION';
export const MODULE_SUBMIT = 'MODULE_SUBMIT';
export const MODULE_CREATE = 'MODULE_CREATE';
export const MODULE_UNLOAD = 'MODULE_UNLOAD';

export const MENU_LOADED = 'MENU_LOADED';
export const MENU_ROLE_LOADED = 'MENU_ROLE_LOADED';
export const MENU_GROUP_LOADED = 'MENU_GROUP_LOADED';
export const MENU_DETAIL_LOADED = 'MENU_DETAIL_LOADED';
export const MENU_UPDATE_FIELD = 'MENU_UPDATE_FIELD';
export const MENU_SUBMIT = 'MENU_SUBMIT';
export const MENU_ADD_GROUP = 'MENU_ADD_GROUP';
export const MENU_CREATE = 'MENU_CREATE';
export const MENU_UPDATE_STATUS = 'MENU_UPDATE_STATUS';
export const MENU_UNLOAD = 'MENU_UNLOAD';

export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_ADMIN_MENU = 'SET_ADMIN_MENU';

export const LIST_MODULE = 'LIST_MODULE';
export const EDIT_MODULE = 'EDIT_MODULE';
export const ADD_MODULE = 'ADD_MODULE';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const SET_ACTION_CODE = 'SET_ACTION_CODE';
export const SET_DISPLAY_NAME = 'SET_DISPLAY_NAME';
export const SET_TYPE = 'SET_TYPE';
export const SET_ACTION_ARR = 'SET_ACTION_ARR';
export const DELETE_ACTION_ARR = 'DELETE_ACTION_ARR';
export const SET_MODULE_CODE = 'SET_MODULE_CODE';
export const SET_MODULE_NAME = 'SET_MODULE_NAME';
export const EDIT_ACTION_ARR = 'EDIT_ACTION_ARR';

export const LIST_POSTOFFICE = 'LIST_POSTOFFICE';
export const GET_POSTOFFICE_BY_ID = 'GET_POSTOFFICE_BY_ID';
export const UPDATE_POSTOFFICE = 'UPDATE_POSTOFFICE';
export const SET_POST_NAME = 'SET_POST_NAME';
export const SET_PHONE = 'SET_PHONE';
export const POSTOFFICE_UNLOADED = 'POST_UNLOADED';
export const POSTOFFICE_LOADED = 'POSTOFFICE_LOADED';
export const POSTOFFICE_DISTRICT_LOADED = 'POSTOFFICE_DISTRICT_LOADED';
export const POSTOFFICE_WARD_LOADED = 'POSTOFFICE_WARD_LOADED';
export const POSTOFFICE_SET_PAGE = 'POSTOFFICE_SET_PAGE';
export const POSTOFFICE_SEARCH = 'POSTOFFICE_SEARCH';
export const POSTOFFICE_DETAIL_LOADED = 'POSTOFFICE_DETAIL_LOADED';
export const POSTOFFICE_DETAIL_SUBMIT = 'POSTOFFICE_DETAIL_SUBMIT';
export const POSTOFFICE_CREATE = 'POSTOFFICE_CREATE';
export const POSTOFFICE_SUBMIT = 'POSTOFFICE_SUBMIT';
export const POSTOFFICE_DELETE = 'POSTOFFICE_DELETE';
export const POSTOFFICE_DETAIL_DELETE = 'POSTOFFICE_DETAIL_DELETE';
export const POSTOFFICE_UPDATE_FIELD = 'POSTOFFICE_UPDATE_FIELD';
export const SET_PAGE = 'SET_PAGE';

export const BILL_LOADED = 'BILL_LOADED';
export const BILL_SET_PAGE = 'BILL_SET_PAGE';
export const BILL_GET_STATUS_NAME = 'BILL_GET_STATUS_NAME';
export const BILL_UNLOADED = 'BILL_UNLOADED';

export const PARTNER_LOADED = 'PARTNER_LOADED';
export const PARTNER_DETAIL_LOADED = 'PARTNER_DETAIL_LOADED';
export const PARTNER_UPDATE_FIELD = 'PARTNER_UPDATE_FIELD';
export const PARTNER_SUBMIT = 'PARTNER_SUBMIT';
export const PARTNER_SET_PAGE = 'PARTNER_SET_PAGE';
export const PARTNER_UNLOADED = 'PARTNER_UNLOADED';

export const ZONE_LOADED = "ZONE_LOADED";
export const ZONE_DETAIL_LOADED = "ZONE_DETAIL_LOADED";
export const ZONE_UPDATE_FIELD = "ZONE_UPDATE_FIELD";
export const ZONE_SUBMIT = "ZONE_SUBMIT";
export const ZONE_CREATE = "ZONE_CREATE";
export const ZONE_DELETE = "ZONE_DELETE";
export const ZONE_SET_PAGE = "ZONE_SET_PAGE";
export const ZONE_UNLOAD = "ZONE_UNLOAD";

export const PROVINCE_LOADED = 'PROVINCE_LOADED';
export const PROVINCE_DETAIL_LOADED = 'PROVINCE_DETAIL_LOADED';
export const PROVINCE_UPDATE_FIELD = 'PROVINCE_UPDATE_FIELD';
export const PROVINCE_SUBMIT = 'PROVINCE_SUBMIT';
export const PROVINCE_CREATE = 'PROVINCE_CREATE';
export const PROVINCE_DELETE = 'PROVINCE_DELETE';
export const PROVINCE_SET_PAGE = 'PROVINCE_SET_PAGE';
export const PROVINCE_UNLOAD = 'PROVINCE_UNLOAD';

export const DISTRICT_LOADED = 'DISTRICT_LOADED';
export const DISTRICT_PROVINCE_LOADED = 'DISTRICT_PROVINCE_LOADED';
export const DISTRICT_DETAIL_LOADED = 'DISTRICT_DETAIL_LOADED';
export const DISTRICT_UPDATE_FIELD = 'DISTRICT_UPDATE_FIELD';
export const DISTRICT_SUBMIT = 'DISTRICT_SUBMIT';
export const DISTRICT_CREATE = 'DISTRICT_CREATE';
export const DISTRICT_DELETE = 'DISTRICT_DELETE';
export const DISTRICT_SET_PAGE = 'DISTRICT_SET_PAGE';
export const DISTRICT_UNLOAD = 'DISTRICT_UNLOAD';

export const WARD_LOADED = 'WARD_LOADED';
export const WARD_DISTRICT_LOADED = 'WARD_DISTRICT_LOADED';
export const WARD_DETAIL_LOADED = 'WARD_DETAIL_LOADED';
export const WARD_UPDATE_FIELD = 'WARD_UPDATE_FIELD';
export const WARD_SUBMIT = 'WARD_SUBMIT';
export const WARD_CREATE = 'WARD_CREATE';
export const WARD_DELETE = 'WARD_DELETE';
export const WARD_SET_PAGE = 'WARD_SET_PAGE';
export const WARD_UNLOAD = 'WARD_UNLOAD';

export const BRANCH_LOADED = "BRANCH_LOADED";
export const BRANCH_DETAIL_LOADED = "BRANCH_DETAIL_LOADED";
export const BRANCH_UPDATE_FIELD = "BRANCH_UPDATE_FIELD";
export const BRANCH_SUBMIT = "BRANCH_SUBMIT";
export const BRANCH_CREATE = "BRANCH_CREATE";
export const BRANCH_FORM = "BRANCH_FORM";
export const BRANCH_APPROVE = "BRANCH_APPROVE";
export const BRANCH_REJECT = "BRANCH_REJECT";
export const BRANCH_DELETE = "BRANCH_DELETE";
export const BRANCH_SET_PAGE = "BRANCH_SET_PAGE";
export const BRANCH_UNLOAD = "BRANCH_UNLOAD";

export const JOB_LOADED = "JOB_LOADED";
export const JOB_DETAIL_LOADED = "JOB_DETAIL_LOADED";
export const JOB_PROVINCE_LOADED = "JOB_PROVINCE_LOADED";
export const JOB_UPDATE_FIELD = "JOB_UPDATE_FIELD";
export const JOB_SUBMIT = "JOB_SUBMIT";
export const JOB_APPROVE = "JOB_APPROVE";
export const JOB_REJECT = "JOB_REJECT";
export const JOB_CREATE = "JOB_CREATE";
export const JOB_FORM = "JOB_FORM";
export const JOB_DELETE = "JOB_DELETE";
export const JOB_SET_PAGE = "JOB_SET_PAGE";
export const JOB_POPUP = "JOB_POPUP";
export const JOB_UNLOAD = "JOB_UNLOAD";

export const DOCUMENT_LOADED = "DOCUMENT_LOADED";
export const DOCUMENT_DETAIL_LOADED = "DOCUMENT_DETAIL_LOADED";
export const DOCUMENT_INTERVIEW_1W = "DOCUMENT_INTERVIEW_1W";
export const DOCUMENT_PROVINCE_LOADED = "DOCUMENT_PROVINCE_LOADED";
export const DOCUMENT_UPDATE_FIELD = "DOCUMENT_UPDATE_FIELD";
export const DOCUMENT_SUBMIT = "DOCUMENT_SUBMIT";
export const DOCUMENT_APPROVE = "DOCUMENT_APPROVE";
export const DOCUMENT_CANCEL = "DOCUMENT_CANCEL";
export const DOCUMENT_CREATE = "DOCUMENT_CREATE";
export const DOCUMENT_DELETE = "DOCUMENT_DELETE";
export const DOCUMENT_SET_PAGE = "DOCUMENT_SET_PAGE";
export const DOCUMENT_UNLOAD = "DOCUMENT_UNLOAD";

export const DOCUMENT_STATUS_LOADED = "DOCUMENT_STATUS_LOADED";
export const DOCUMENT_STATUS_DETAIL_LOADED = "DOCUMENT_STATUS_DETAIL_LOADED";
export const DOCUMENT_STATUS_UPDATE_FIELD = "DOCUMENT_STATUS_UPDATE_FIELD";
export const DOCUMENT_STATUS_SUBMIT = "DOCUMENT_STATUS_SUBMIT";
export const DOCUMENT_STATUS_CREATE = "DOCUMENT_STATUS_CREATE";
export const DOCUMENT_STATUS_DELETE = "DOCUMENT_STATUS_DELETE";
export const DOCUMENT_STATUS_UNLOAD = "DOCUMENT_STATUS_UNLOAD";

export const NEWS_LOADED = "NEWS_LOADED";
export const NEWS_DETAIL_LOADED = "NEWS_DETAIL_LOADED";
export const NEWS_PROVINCE_LOADED = "NEWS_PROVINCE_LOADED";
export const NEWS_UPDATE_FIELD = "NEWS_UPDATE_FIELD";
export const NEWS_SUBMIT = "NEWS_SUBMIT";
export const NEWS_APPROVE = "NEWS_APPROVE";
export const NEWS_CREATE = "NEWS_CREATE";
export const NEWS_FORM = "NEWS_FORM";
export const NEWS_DELETE = "NEWS_DELETE";
export const NEWS_SET_PAGE = "NEWS_SET_PAGE";
export const NEWS_UNLOAD = "NEWS_UNLOAD";

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
